export const songsList = [
  {
    id: 1,
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    genre: "Pop",
  },
  {
    id: 2,
    title: "Save Your Tears",
    artist: "The Weeknd & Ariana Grande",
    album: "After Hours",
    genre: "Pop",
  },
  {
    id: 3,
    title: "Dynamite",
    artist: "BTS",
    album: "BE",
    genre: "Pop",
  },
  {
    id: 4,
    title: "Positions",
    artist: "Ariana Grande",
    album: "Positions",
    genre: "R&B",
  },
  {
    id: 5,
    title: "Stay",
    artist: "The Kid LAROI ft. Justin Bieber",
    album: "F*ck Love 3: Over You",
    genre: "Pop Rap",
  },
  {
    id: 6,
    title: "Heat Waves",
    artist: "Glass Animals",
    album: "Dreamland",
    genre: "Indie Rock",
  },
  {
    id: 7,
    title: "Beat It",
    artist: "Michael Jackson",
    album: "Thriller",
    genre: "Pop",
  },
  {
    id: 8,
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    genre: "Pop",
  },
  {
    id: 9,
    title: "Rolling in the Deep",
    artist: "Adele",
    album: "21",
    genre: "Pop",
  },
  {
    id: 10,
    title: "Happier Than Ever",
    artist: "Billie Eilish",
    album: "Happier Than Ever",
    genre: "Alternative/Indie",
  },
];
